# Generated by Django 3.0.1 on 2020-03-21 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='activity_date',
            field=models.DateTimeField(default=datetime.date(2020, 3, 21)),
        ),
    ]
